### PR TITLE
fix: go 1.19 panic: Unexpected package creation during export data loading

### PR DESCRIPTION
**Pull request by ttys3**
can not run under go 1.19

go version go1.19 linux/amd64

```shell
./logrlint .
logrlint: Unexpected package creation during export data loading
```

update to golang.org/x/tools v0.1.12

ref:

https://github.com/go-delve/delve/pull/3053

https://github.com/golang/go/issues/45218

### CODE REVIEW

**Comment by ttys3** [comment]
@timonwong  rebased and resolved conflict now.

I hope this could merged because without this merged I can not run logrlint locally

**Comment by timonwong** [comment]
This PR is ok. one caveat is that after merging the "plugin" cannot work with prior versions of golangci-lint

**Comment by timonwong** [comment]
go mod tidy is required

**Comment by ttys3** [comment]
@timonwong tidy done, the workflow need approved again

**Review by timonwong — APPROVED** [review]
LGTM

**Comment by timonwong** [comment]
Thanks :)

**Pull request merged**
